# Generated by Django 4.1.2 on 2022-10-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('mailAdd', models.EmailField(max_length=254)),
                ('employedDT', models.DateField()),
                ('employeeID', models.CharField(max_length=14)),
            ],
        ),
    ]
